const guides=[1,2,3,51,52,53,176,177,178];
const path=location.pathname.replace(/\/$/,'')||'/';
const book=path.includes('/tt02')?'tt02':'tt01';
const title=book==='tt01'?'Classic Train Tracks':'Classic Train Tracks: Volume Two';
const pad=n=>String(n).padStart(3,'0');
const header=`<header class="masthead"><div class="shell"><a class="brand" href="/books/tt01">Peter <span>Kelby</span></a><nav><a href="/books/tt01">Book one</a><a href="/books/tt02">Book two</a><a href="/logicacademy/signup">Logic Academy</a></nav></div></header>`;
const footer=`<footer class="footer"><div class="shell">© ${new Date().getFullYear()} Peter Kelby · <a href="/books/${book}/guides">Puzzle guides</a></div></footer>`;
const guidesList=guides.map(n=>`<li><a href="/books/${book}/guide_${pad(n)}">Puzzle ${pad(n)}</a></li>`).join('');
function layout(body){document.querySelector('#app').innerHTML=header+body+footer}
function signup(kind='Logic Academy'){return `<section class="content"><div class="shell"><p class="eyebrow">Free to join</p><h1>${kind}</h1><p class="lead">Get practical puzzle tips, book news, and occasional extras from Peter Kelby.</p><form name="${kind.toLowerCase().replaceAll(' ','-')}-signup" method="POST" data-netlify="true" action="/thanks"><input type="hidden" name="form-name" value="${kind.toLowerCase().replaceAll(' ','-')}-signup"><label for="name">First name</label><input id="name" name="name" autocomplete="given-name"><label for="email">Email address</label><input id="email" type="email" name="email" autocomplete="email" required><p><button class="button" type="submit">Send me the free guide</button></p></form><p class="notice">This form is ready for Netlify Forms. Connect its submissions to your email service after deployment.</p></div></section>`}
if(path==='/logicacademy/signup') layout(signup());
else if(path.endsWith('/sample')) layout(signup(`${title} sample`));
else if(path.endsWith('/guides')) layout(`<section class="content"><div class="shell"><p class="eyebrow">${title}</p><h1>Step-by-step puzzle guides</h1><p>Choose a puzzle below for a calm, methodical walkthrough. More guides will be added as the collection grows.</p><ol class="guide-list">${guidesList}</ol></div></section>`);
else if(/\/guide_\d+$/.test(path)){const n=Number(path.match(/\d+$/)[0]);layout(`<section class="content"><div class="shell"><p class="eyebrow">${title} · Guide ${pad(n)}</p><h1>Puzzle ${pad(n)}</h1><p class="lead">A clear route into this puzzle—without taking away the satisfaction of solving it yourself.</p><div class="rail"></div><ol class="steps"><li>Start with the rows or columns with the fewest possible track arrangements. Mark the clues that give you the strongest constraints.</li><li>Use the confirmed track pieces to eliminate impossible turns from the neighbouring squares.</li><li>Follow each newly fixed section one square at a time. Every track must join cleanly and the route cannot branch.</li><li>Check that your final network has no loose ends or smaller closed loops. Then compare it with the solution in the book.</li></ol><p class="notice">This is the guide framework. The exact illustrated moves for puzzle ${pad(n)} can be added once Peter approves the final puzzle artwork and solution sequence.</p><a class="button alt" href="/books/${book}/guides">All guides</a></div></section>`)}
else if(/^\/books\/tt0[12]$/.test(path))layout(`<section class="hero"><div class="shell"><p class="eyebrow">Peter Kelby presents</p><h1>${title}</h1><p class="lead">Thoughtful, absorbing logic puzzles for railway enthusiasts and anyone who enjoys a satisfying route to the answer.</p><a class="button" href="/books/${book}/guides">Explore the puzzle guides</a></div></section><section class="content"><div class="shell"><h2>Make tracks. Find the route.</h2><div class="cards"><article class="card"><h3>Need a nudge?</h3><p>Open a guide for selected puzzles, with the reasoning explained one move at a time.</p><a class="button alt" href="/books/${book}/guides">View guides</a></article><article class="card"><h3>Try a sample</h3><p>Join the mailing list for a free sample and future puzzle news.</p><a class="button alt" href="/books/${book}/sample">Get the sample</a></article></div></div></section>`);
else if(path==='/thanks')layout(`<section class="content"><div class="shell"><h1>You’re on the list.</h1><p class="lead">Thanks for signing up. Please check your inbox for the next step.</p><a class="button" href="/books/tt01">Explore the books</a></div></section>`);
else layout(`<section class="hero"><div class="shell"><p class="eyebrow">Logic puzzles by</p><h1>Peter Kelby</h1><p class="lead">Train Tracks logic-puzzle books made for quiet concentration and satisfying solutions.</p><a class="button" href="/books/tt01">Discover the books</a></div></section>`);
