[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "https://geni.us/pk-author-page"
  status = 301
  force = true

[[redirects]]
  from = "/tt01"
  to = "https://geni.us/pk-tt01-buy"
  status = 301

[[redirects]]
  from = "/tt02"
  to = "https://geni.us/pk-tt02-buy"
  status = 301

[[redirects]]
  from = "/review/tt01"
  to = "https://geni.us/pk-tt01-review"
  status = 301

[[redirects]]
  from = "/review/tt02"
  to = "https://geni.us/pk-tt02-review"
  status = 301

[[redirects]]
  from = "/books/tt01/guide_001"
  to = "/books/tt01/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_001/"
  to = "/books/tt01/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_002"
  to = "/books/tt01/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_002/"
  to = "/books/tt01/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
