[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "https://geni.us/pk-author-page"
  status = 301
  force = true

[[redirects]]
  from = "/tt01/guide_*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/tt02/guide_*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/tt02/guide_*"
  to = "/books/tt02/guide_:splat"
  status = 301

[[redirects]]
  from = "/tt01/guides"
  to = "/books/tt01/guides"
  status = 301

[[redirects]]
  from = "/tt02/guides"
  to = "/books/tt02/guides"
  status = 301

[[redirects]]
  from = "/tt01"
  to = "https://geni.us/pk-tt01-buy"
  status = 301

[[redirects]]
  from = "/tt02"
  to = "https://geni.us/pk-tt02-buy"
  status = 301

[[redirects]]
  from = "/tt01/*"
  to = "/books/tt01/:splat"
  status = 301

[[redirects]]
  from = "/tt02/*"
  to = "/books/tt02/:splat"
  status = 301

[[redirects]]
  from = "/review/tt01"
  to = "https://geni.us/pk-tt01-review"
  status = 301

[[redirects]]
  from = "/review/tt02"
  to = "https://geni.us/pk-tt02-review"
  status = 301

[[redirects]]
  from = "/books/tt01/guide_001"
  to = "/books/tt01/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_001/"
  to = "/books/tt01/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_002"
  to = "/books/tt01/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_002/"
  to = "/books/tt01/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_051"
  to = "/books/tt01/guide_051/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_051/"
  to = "/books/tt01/guide_051/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_052"
  to = "/books/tt01/guide_052/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_052/"
  to = "/books/tt01/guide_052/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guides"
  to = "/books/tt01/guides/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guides/"
  to = "/books/tt01/guides/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/tt01/guides"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/tt01/guides/"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/tt02/guides"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/tt02/guides/"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/logicacademy/signup"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/logicacademy/signup/"
  to = "/errors/guide-not-found.html"
  status = 404
  force = true

[[redirects]]
  from = "/books/tt02/guides"
  to = "/books/tt02/guides/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guides/"
  to = "/books/tt02/guides/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_001"
  to = "/books/tt02/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_001/"
  to = "/books/tt02/guide_001/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_002"
  to = "/books/tt02/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_002/"
  to = "/books/tt02/guide_002/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_051"
  to = "/books/tt02/guide_051/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_051/"
  to = "/books/tt02/guide_051/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_052"
  to = "/books/tt02/guide_052/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_052/"
  to = "/books/tt02/guide_052/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_176"
  to = "/books/tt02/guide_176/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_176/"
  to = "/books/tt02/guide_176/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_177"
  to = "/books/tt02/guide_177/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt02/guide_177/"
  to = "/books/tt02/guide_177/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_176"
  to = "/books/tt01/guide_176/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_176/"
  to = "/books/tt01/guide_176/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_177"
  to = "/books/tt01/guide_177/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/books/tt01/guide_177/"
  to = "/books/tt01/guide_177/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pda/signup"
  to = "/pda/signup/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pda/signup/"
  to = "/pda/signup/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pda/signup/thanks"
  to = "/pda/signup/thanks/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pda/signup/thanks/"
  to = "/pda/signup/thanks/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
